version: "2.4"

services:
  node:
    image: ${REGISTRY}node:${NODE_VERSION}-nanoserver-${NANOSERVER_VERSION}
    command: ['cmd.exe', '/c', 'ping -n 1800 127.0.0.1 >NUL']
    build:
      context: ./docker/build/node
      args:
        BASE_IMAGE: mcr.microsoft.com/windows/nanoserver:${NANOSERVER_VERSION}
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - .\theme:C:\theme